import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import { generatePlanCandidates, planTemplates } from "../lib/plan-generator";

const input = {
  site: { northDirection: "北", entranceDirection: "南", roadDirections: ["南"], boundaryConfirmed: true, areaSquareMeters: 432, perimeterMeters: 84, boundaryPoints: [{ x: 0, y: 0 }, { x: 18000, y: 0 }, { x: 18000, y: 24000 }, { x: 0, y: 24000 }] },
  requirements: { floors: 1, householdSize: 3, areaMin: 75, areaMax: 95, bedroomCount: 2, bathroomCount: 1, stairCount: 0, elderRoomCount: 1, elderRoomFirstFloor: true, minBedroomArea: 8, minElderRoomArea: 10, minLivingArea: 15, minKitchenArea: 5, minBathroomArea: 3, priorities: ["适老", "动静分区"], notes: "" },
} as const;

test("loads all fifteen approved mature templates", () => { assert.deepEqual(planTemplates.map(x => x.id), ["HT-T001", "HT-T002", "HT-T003", "HT-T004", "HT-T005", "HT-T006", "HT-T007", "HT-T008", "HT-T009", "HT-T010", "HT-T011", "HT-T012", "HT-T013", "HT-T014", "HT-T015"]); assert.ok(planTemplates.every(x => x.status === "APPROVED")); });
test("each mature template references a real standardized DXF", async () => { for (const template of planTemplates) { const source = await readFile(`resources/house-templates/${template.source.dxfPath}`, "utf8"); assert.match(source, /SECTION/); assert.match(source, /ENTITIES/); assert.ok(template.rooms.length >= 6); assert.ok(template.walls.length > 20); } });
test("returns candidates rendered from mature template geometry", () => { const plans = generatePlanCandidates(input as never); assert.equal(plans.length, 3); for (const plan of plans) { assert.match(plan.templateId, /^HT-T0(?:0[1-9]|1[0-5])$/); assert.match(plan.templateSource, /STANDARDIZED_AC1032\.dxf/); assert.match(plan.svg, /成熟DXF户型及总尺寸/); assert.match(plan.svg, /data-layer="OVERALL_DIMENSIONS"/); assert.doesNotMatch(plan.svg, /data-layer="AXIS_GRID"/); assert.doesNotMatch(plan.svg, /data-layer="GRID_DIMENSIONS"/); assert.match(plan.svg, /总宽/); assert.match(plan.svg, /总深/); assert.ok(plan.rooms.length >= 6); assert.equal(plan.siteFit.fits, true); } });
test("supports approved two-floor templates without synthesizing rooms", () => { const twoFloor = structuredClone(input) as any; Object.assign(twoFloor.site, { areaSquareMeters: 900, perimeterMeters: 120, boundaryPoints: [{ x: 0, y: 0 }, { x: 30000, y: 0 }, { x: 30000, y: 30000 }, { x: 0, y: 30000 }] }); Object.assign(twoFloor.requirements, { floors: 2, bedroomCount: 4, areaMin: 180, areaMax: 280 }); const plans = generatePlanCandidates(twoFloor); assert.ok(plans.length > 0); assert.ok(plans.every(plan => plan.floors === 2)); assert.ok(plans.every(plan => plan.rooms.some(room => room.floor === 2))); assert.match(plans[0].svg, /data-floor-footprint="2"/); });
test("rejects mature candidates that cannot fit the buildable polygon", () => { const constrained = structuredClone(input) as any; constrained.site.buildablePoints = [{ x: 0, y: 0 }, { x: 4000, y: 0 }, { x: 4000, y: 4000 }, { x: 0, y: 4000 }]; constrained.site.buildableAreaSquareMeters = 16; assert.equal(generatePlanCandidates(constrained).length, 0); });
test("centers every room label without a main entrance annotation", () => { const plans = generatePlanCandidates(input as never); for (const plan of plans) { assert.equal((plan.svg.match(/data-label-position="visual-center"/g) ?? []).length, plan.rooms.length); assert.doesNotMatch(plan.svg, /data-layer="MAIN_ENTRANCE"/); assert.doesNotMatch(plan.svg, />主入口<\/text>/); } });
test("describes residential strengths and shortcomings instead of technical provenance", () => { const plans = generatePlanCandidates(input as never); for (const plan of plans) { assert.ok(plan.strengths.length >= 2); assert.ok(plan.tradeoffs.length >= 1); assert.ok(plan.strengths.some(item => /卧|客厅|餐厅|主卧|厨房|玄关|储藏/.test(item))); assert.ok(plan.tradeoffs.some(item => /老人房|卧室|卫生间|玄关|阳台|家政|净尺寸/.test(item))); assert.doesNotMatch(plan.strengths.join(" "), /DXF|模板来源|整体调正/); assert.doesNotMatch(plan.tradeoffs.join(" "), /未改变成熟模板内部布局/); } });
test("renders dimension-matched doors and windows with coordinated colors", () => { const plans = generatePlanCandidates(input as never); for (const plan of plans) { const template = planTemplates.find(item => item.id === plan.templateId)!; assert.equal((plan.svg.match(/data-opening-type="door"/g) ?? []).length, template.openings.filter(item => item.type.includes("DOOR")).length); assert.equal((plan.svg.match(/data-opening-type="window"/g) ?? []).length, template.openings.filter(item => item.type.includes("WINDOW")).length); assert.match(plan.svg, /data-opening-type="door"[^>]+data-door-type="(?:single-swing-inward|sliding)"[^>]+data-opening-length-mm="\d+"[^>]+stroke="#e2ca7a"/); assert.match(plan.svg, /data-door-type="single-swing-inward"/); assert.match(plan.svg, /data-door-leaf="true"/); assert.match(plan.svg, /data-door-swing="true"/); assert.match(plan.svg, /data-opening-type="window"[^>]+data-opening-length-mm="\d+"[^>]+stroke="#9ebdca"/); assert.match(plan.svg, /stroke="#454b49"/); } });

test("derives swing and sliding door types from original DXF blocks", () => { const previewInput = structuredClone(input) as any; Object.assign(previewInput.site, { areaSquareMeters: 600, perimeterMeters: 100, boundaryPoints: [{ x: 0, y: 0 }, { x: 25000, y: 0 }, { x: 25000, y: 24000 }, { x: 0, y: 24000 }] }); Object.assign(previewInput.requirements, { areaMin: 90, areaMax: 150, bedroomCount: 3, bathroomCount: 2, elderRoomCount: 0, elderRoomFirstFloor: false }); const plan = generatePlanCandidates(previewInput).find(item => item.templateId === "HT-T005")!; assert.ok(plan); const template = planTemplates.find(item => item.id === "HT-T005")!; assert.equal((plan.svg.match(/data-door-type="single-swing-inward"/g) ?? []).length, template.openings.filter(item => item.sourceBlock === "$DorLib2D$00000001").length); assert.equal((plan.svg.match(/data-door-type="sliding"/g) ?? []).length, template.openings.filter(item => item.sourceBlock === "$DorLib2D$00000131").length); assert.match(plan.svg, /data-door-type="single-swing-inward"[^>]+data-source-block="\$DorLib2D\$00000001"/); assert.match(plan.svg, /data-door-type="sliding"[^>]+data-source-block="\$DorLib2D\$00000131"/); });

test("groups room fills by architectural use and bleeds color to wall edges", () => { const plans = generatePlanCandidates(input as never); for (const plan of plans) { assert.match(plan.svg, /data-room-category="service-base"[^>]+fill="#ddd9d0"/); assert.match(plan.svg, /data-room-category="private"[^>]*><polygon[^>]+fill="#dfe8d6"[^>]+stroke="#dfe8d6"[^>]+stroke-width="40"/); assert.match(plan.svg, /data-room-category="public"[^>]*><polygon[^>]+fill="#efe1cc"[^>]+stroke="#efe1cc"[^>]+stroke-width="40"/); assert.match(plan.svg, /data-room-category="service"[^>]*><polygon[^>]+fill="#ddd9d0"[^>]+stroke="#ddd9d0"[^>]+stroke-width="40"/); } });

test("renders reviewed porch, terrace, and exterior steps outside the main footprint", () => { const previewInput = structuredClone(input) as any; Object.assign(previewInput.site, { areaSquareMeters: 600, perimeterMeters: 100, boundaryPoints: [{ x: 0, y: 0 }, { x: 25000, y: 0 }, { x: 25000, y: 24000 }, { x: 0, y: 24000 }] }); Object.assign(previewInput.requirements, { areaMin: 90, areaMax: 150, bedroomCount: 3, bathroomCount: 2, elderRoomCount: 0, elderRoomFirstFloor: false }); const plan = generatePlanCandidates(previewInput).find(item => item.templateId === "HT-T005")!; assert.match(plan.svg, /data-ancillary-type="PORCH"[^>]+data-area-square-meters="8.55"/); assert.match(plan.svg, /data-ancillary-type="OUTDOOR-TERRACE"[^>]+data-area-square-meters="12.95"/); assert.match(plan.svg, /data-ancillary-type="EXTERIOR-STEPS"[^>]+data-side-closure="both"/); assert.match(plan.svg, /data-ancillary-type="CURVED-EXTERIOR-STEPS"[^>]+data-tread-layout="parallel"[^>]+data-area-square-meters="0.86"/); assert.equal((plan.svg.match(/data-parallel-tread="true"/g) ?? []).length, 3); });
